/*
 * The MIT License
 *
 * Copyright 2015 Sergio.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.lajuderia.views;

import java.awt.event.ActionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Sergio
 */
public class GameListView extends javax.swing.JFrame {
    /**
     * Creates new form jpMain
     */
    public GameListView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtGames = new javax.swing.JTable();
        lbStatus = new javax.swing.JLabel();
        btLoadXML = new javax.swing.JButton();
        btImportFromSteam = new javax.swing.JButton();
        btSaveXML = new javax.swing.JButton();
        btMetacritic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtGames.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(jtGames);

        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("LabelsBundle"); // NOI18N
        btLoadXML.setText(bundle.getString("LOAD_GAMES")); // NOI18N
        btLoadXML.setToolTipText("");

        btImportFromSteam.setText(bundle.getString("IMPORT_GAMES_FROM_STEAM")); // NOI18N

        btSaveXML.setText(bundle.getString("SAVE_GAMES")); // NOI18N
        btSaveXML.setToolTipText("");

        btMetacritic.setText(bundle.getString("IMPORT_METACRITIC")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLoadXML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSaveXML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImportFromSteam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMetacritic)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbStatus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLoadXML)
                    .addComponent(btImportFromSteam)
                    .addComponent(btSaveXML)
                    .addComponent(btMetacritic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setStatusBarMessage(String message){
        this.lbStatus.setText(message);
    }
    
    public void registerListener(ActionListener listener){
        this.btLoadXML.addActionListener(listener);
        this.btImportFromSteam.addActionListener(listener);
        this.btSaveXML.addActionListener(listener);
        this.btMetacritic.addActionListener(listener);
    }
    
    public void setTableModel(TableModel tableModel) {
       jtGames.setModel(tableModel);
    }
    
    public Object getTableValueAt(int row, int column){
        return ( jtGames.getModel().getValueAt(
                jtGames.convertRowIndexToModel(row),
                column)
            ) ;
    }
    
    public void setMessageStatus(String message) {
        lbStatus.setText(message);
    }
    
    public int[] getSelectedTableRows() {
        return ( jtGames.getSelectedRows() );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImportFromSteam;
    private javax.swing.JButton btLoadXML;
    private javax.swing.JButton btMetacritic;
    private javax.swing.JButton btSaveXML;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtGames;
    private javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables
  

}
